import { MenuItem, PizzaSizeOption, CrustOption, FlavorOption, ToppingOption } from './types';
import garlicRanchImg from './assets/images/garlic_ranch_dip_1780675118166.png';
import coke15Img from './assets/images/coca_cola_1_5l_1780675573134.png';
import spriteCanImg from './assets/images/sprite_can_345ml_1780675591187.png';

export const PIZZA_SIZES: PizzaSizeOption[] = [
  {
    id: 'size_small',
    name: '6" Personal',
    slices: 4,
    priceBase: 490,
    description: 'Perfect for single-person cravings. Includes 4 fluffy slices.',
  },
  {
    id: 'size_medium',
    name: '10" Medium',
    slices: 6,
    priceBase: 1090,
    description: 'Great for sharing between 2 people. Includes 6 slices.',
  },
  {
    id: 'size_large',
    name: '13" Large',
    slices: 8,
    priceBase: 1690,
    description: 'The standard choice for family nights. Includes 8 generous slices.',
  },
  {
    id: 'size_beast',
    name: '20" Pizza Master Beast',
    slices: 12,
    priceBase: 2890,
    description: 'Pakistan\'s largest iconic pizza! 12 massive rectangular slices.',
  },
];

export const CRUSTS: CrustOption[] = [
  { id: 'crust_tossed', name: 'Original Hand Tossed', priceUpsell: 0 },
  { id: 'crust_pan', name: 'Deep Dish Pan Crust', priceUpsell: 50 },
  { id: 'crust_garlic', name: 'Garlic Butter Edge', priceUpsell: 120 },
  { id: 'crust_stuffed', name: 'Cheese Stuffed Crust', priceUpsell: 290 },
];

export const FLAVORS: FlavorOption[] = [
  {
    id: 'flavor_phantom',
    name: 'Phantom (Signature Spicy)',
    description: 'Smoked black pepper ranch sauce, chicken tandoori chunks, roasted onions, black olives, and spicy jalapenos.',
    heatLevel: 3,
  },
  {
    id: 'flavor_tikka',
    name: 'Extreme Tikka Blast',
    description: 'Traditional Pakistani spiced chicken tikka bites, bell peppers, fresh sliced onions, and a creamy mint raita drizzle.',
    heatLevel: 2,
  },
  {
    id: 'flavor_special',
    name: 'Pizza Master Special',
    description: 'Premium beef pepperoni slices, smoked chicken slivers, fresh button mushrooms, green peppers, black olives, sweet corn, and marinara.',
    heatLevel: 1,
  },
  {
    id: 'flavor_garlic_ranch',
    name: 'West Side Ranch Garlic',
    description: 'Thick white garlic ranch sauce base, grilled herb chicken, premium mushrooms, light tomatoes, and extra mozzarella.',
    heatLevel: 0,
  },
  {
    id: 'flavor_sriracha_lava',
    name: 'Wicked Sriracha Lava',
    description: 'Fiery sweet-heat Sriracha base sauce, spicy chicken fajita pieces, red jalapeño rings, green peppers, and a hot honey drizzle.',
    heatLevel: 3,
  },
  {
    id: 'flavor_margherita',
    name: 'Classic Margherita',
    description: 'Simple and elegant. Rich marinara, double premium mozzarella, sliced fresh tomatoes, and an Italian herb drizzle.',
    heatLevel: 0,
  },
];

export const TOPPINGS: ToppingOption[] = [
  // Meats
  { id: 'top_smoked_chicken', name: 'Smoked Chicken', category: 'meat', price: 160 },
  { id: 'top_tikka_chicken', name: 'Tikka Chicken Chunks', category: 'meat', price: 160 },
  { id: 'top_pepperoni', name: 'Beef Pepperoni', category: 'meat', price: 180 },
  { id: 'top_beef_mince', name: 'Spicy Beef Mince', category: 'meat', price: 170 },
  // Veggies
  { id: 'top_olives', name: 'Black Olives', category: 'veg', price: 90 },
  { id: 'top_mushrooms', name: 'Button Mushrooms', category: 'veg', price: 90 },
  { id: 'top_jalapenos', name: 'Spicy Jalapeños', category: 'veg', price: 90 },
  { id: 'top_bell_peppers', name: 'Green Bell Peppers', category: 'veg', price: 70 },
  { id: 'top_onions', name: 'Fresh Red Onions', category: 'veg', price: 70 },
  { id: 'top_corn', name: 'Sweet Golden Corn', category: 'veg', price: 80 },
  // Cheese
  { id: 'top_extra_mozzarella', name: 'Extra Premium Mozzarella', category: 'cheese', price: 220 },
  { id: 'top_cheddar', name: 'Cheddar Blend Accent', category: 'cheese', price: 180 },
];

export const MENU_ITEMS: MenuItem[] = [
  // --- DEALS ---
  {
    id: 'deal_solos',
    name: 'Solo Pizza Master Deal',
    description: 'Unmatched value for one! 1 Small Pizza (6", any flavor, custom crust) + 1 Coca-Cola 345ml Can.',
    category: 'deals',
    price: 590,
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&q=80&w=600',
    isPizza: true, // customizable pizza!
    isPopular: true,
    sizes: [PIZZA_SIZES[0]], // Only Small size applies
    crusts: CRUSTS,
    flavors: FLAVORS,
    toppings: TOPPINGS,
    dealItems: ['1x Small 6" Customized Pizza', '1x 345ml Soft Drink Can'],
  },
  {
    id: 'deal_duo',
    name: 'Pizza Master Double Trouble',
    description: 'The perfect date night deal. 2 Medium Pizzas (10", any flavors, custom crusts) + 1 Garlic Bread Base + 1 Litre Soft Drink.',
    category: 'deals',
    price: 1990,
    image: 'https://images.unsplash.com/photo-1590947132387-155cc02f3212?auto=format&fit=crop&q=80&w=600',
    isPizza: true,
    sizes: [PIZZA_SIZES[1]], // Medium Pizza customizable
    crusts: CRUSTS,
    flavors: FLAVORS,
    toppings: TOPPINGS,
    dealItems: ['2x 10" Medium Customized Pizzas', '1x Roasted Garlic Bread', '1x 1-Litre Beverage Bottled'],
  },
  {
    id: 'deal_beast',
    name: 'Pizza Master Beast Banquet',
    description: 'Unleash the Beast! 1 gigantic Pizza Master Beast 20" Pizza (choose up to 2 crust sizes/flavors) + 1 Spicy Baked Buffalo-Wings (6pcs) + 1.5L Soft Drink.',
    category: 'deals',
    price: 3490,
    image: 'https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?auto=format&fit=crop&q=80&w=600',
    isPizza: true,
    isPopular: true,
    sizes: [PIZZA_SIZES[3]], // Only Beast size
    crusts: CRUSTS,
    flavors: FLAVORS,
    toppings: TOPPINGS,
    dealItems: ['1x Massive 20" Pizza Master Beast Pizza', '1x Crispy Baked Wings (6 pcs)', '1x 1.5L Soft Drink Bottle'],
  },
  {
    id: 'deal_family',
    name: 'Grand Family Pizza Master Night',
    description: 'Feast like royalty. 2 Large Pizzas (13", any flavors, custom crusts) + loaded cheese potato skins + 1.5 Litre Soft Drink.',
    category: 'deals',
    price: 3890,
    image: 'https://images.unsplash.com/photo-1604152135912-04a022e23696?auto=format&fit=crop&q=80&w=600',
    isPizza: true,
    sizes: [PIZZA_SIZES[2]], // Large
    crusts: CRUSTS,
    flavors: FLAVORS,
    toppings: TOPPINGS,
    dealItems: ['2x 13" Large Customized Pizzas', '1x Loaded Cheesy Potato Skins', '1x 1.5L Beverage Bottle'],
  },

  // --- PIZZAS ---
  {
    id: 'pizza_phantom',
    name: 'The Phantom (Signature)',
    description: 'Our ultimate smoke-black pepper base sauce, lavishly topped with tender spiced tandoori chicken, Spanish onions, ripe black olives, spicy bell peppers, and premium mozzarella cheese on a golden crust.',
    category: 'pizzas',
    price: 1090, // Shows medium base price as default
    image: 'https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?auto=format&fit=crop&q=80&w=600',
    isPizza: true,
    isPopular: true,
    sizes: PIZZA_SIZES,
    crusts: CRUSTS,
    flavors: FLAVORS,
    toppings: TOPPINGS,
  },
  {
    id: 'pizza_tikka',
    name: 'Extreme Chicken Tikka Blast',
    description: 'Savor the local spice! Tangy marinated oven-fired chicken tikka breast chunks, red onions, fresh green peppers, finished with mozzarella, and a generous swirl of cool garlic-mint sauce.',
    category: 'pizzas',
    price: 1090,
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&q=80&w=600',
    isPizza: true,
    sizes: PIZZA_SIZES,
    crusts: CRUSTS,
    flavors: FLAVORS,
    toppings: TOPPINGS,
  },
  {
    id: 'pizza_special',
    name: 'Pizza Master Special Legend',
    description: 'The pizza that started it all. Loaded with premium hot beef pepperoni, oven-smoked chicken chunks, green peppers, tender mushrooms, black sliced olives, sweet sweet corn, and double mozzarella stretch.',
    category: 'pizzas',
    price: 1090,
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&q=80&w=600',
    isPizza: true,
    isPopular: true,
    sizes: PIZZA_SIZES,
    crusts: CRUSTS,
    flavors: FLAVORS,
    toppings: TOPPINGS,
  },
  {
    id: 'pizza_ranch',
    name: 'West Side Ranch Garlic',
    description: 'Ditch the red sauce for our epic creamy white ranch base! Loaded with perfectly seasoned grilled chicken slices, button mushrooms, ripe tomatoes, sweet onions, and an elegant mozzarella coat.',
    category: 'pizzas',
    price: 1090,
    image: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?auto=format&fit=crop&q=80&w=600',
    isPizza: true,
    sizes: PIZZA_SIZES,
    crusts: CRUSTS,
    flavors: FLAVORS,
    toppings: TOPPINGS,
  },
  {
    id: 'pizza_lava',
    name: 'Wicked Sriracha Lava',
    description: 'Sweet, smoky, and dangerously hot! Deep red chili Sriracha base, roasted spicy chicken chunks, pickled hot jalapeños, bell peppers, melted cheddar blend, finished with sweet hot honey swirl.',
    category: 'pizzas',
    price: 1090,
    image: 'https://images.unsplash.com/photo-1585238342024-78d387f4a707?auto=format&fit=crop&q=80&w=600',
    isPizza: true,
    sizes: PIZZA_SIZES,
    crusts: CRUSTS,
    flavors: FLAVORS,
    toppings: TOPPINGS,
  },
  {
    id: 'pizza_margherita',
    name: 'Classic Margherita Premium',
    description: 'A masterpiece under simplicity. Fresh rich tomato marinara, a thick layer of melted Italian style mozzarella cheese, fresh basil extracts, sliced tomatoes, and extra virgin olive oil.',
    category: 'pizzas',
    price: 990,
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&q=80&w=600',
    isPizza: true,
    sizes: PIZZA_SIZES,
    crusts: CRUSTS,
    flavors: FLAVORS,
    toppings: TOPPINGS,
  },

  // --- STARTERS & SIDES ---
  {
    id: 'starter_garlic_bread',
    name: 'Garlic Bread Supreme',
    description: 'Crispy oven-roasted toasted baguettes topped with fragrant loaded garlic butter, fresh parsley, and melted bubbly mozzarella cheese.',
    category: 'starters',
    price: 380,
    image: 'https://images.unsplash.com/photo-1608039829572-78524f79c4c7?auto=format&fit=crop&q=80&w=600',
    isPizza: false,
  },
  {
    id: 'starter_buffalo_wings',
    name: 'Fiery Buffalo Wings',
    description: '6 pieces of golden fried jumbo chicken wings, sauced and glazed in our special tangy hot Buffalo blend, served with garlic mayo dip.',
    category: 'starters',
    price: 520,
    image: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?auto=format&fit=crop&q=80&w=600',
    isPizza: false,
    isPopular: true,
  },
  {
    id: 'starter_potato_skins',
    name: 'Oven Loaded Potato Skins',
    description: '4 pieces of crispy, hollowed-out potato skins, baked with smoke chicken crumbs, chopped jalapeños, and loaded melted cheese cheddar blend.',
    category: 'starters',
    price: 450,
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&q=80&w=600',
    isPizza: false,
  },
  {
    id: 'starter_loaded_fries',
    name: 'Pizza Master Loaded Fries',
    description: 'Gold-standard fries! Golden crinkle fries baked with secret pasta sauce, spicy chicken shredding, jalapenos, and a thick cheese pull blanket.',
    category: 'starters',
    price: 590,
    image: 'https://images.unsplash.com/photo-1585109649139-366815a0d713?auto=format&fit=crop&q=80&w=600',
    isPizza: false,
  },

  // --- PASTA ---
  {
    id: 'pasta_alfredo',
    name: 'Pizza Master Alfredo Dream',
    description: 'Silky smooth Fettuccine pasta tossed in premium heavy cream, fresh garlic, ground black pepper, and butter white roux, topped with generous grilled chicken breast steaks, mushrooms, and warm garlic breadsticks.',
    category: 'pasta',
    price: 890,
    image: 'https://images.unsplash.com/photo-1645112411341-6c4fd023714a?auto=format&fit=crop&q=80&w=600',
    isPizza: false,
    isPopular: true,
  },
  {
    id: 'pasta_tandoori',
    name: 'Baked Chicken Tandoori Pasta',
    description: 'Oven-baked Penne pasta coated in rich, mildly spicy desi-style tandoori cream sauce with roasted red onions, bell peppers, juicy chicken, covered in high-stretch baked cheese.',
    category: 'pasta',
    price: 850,
    image: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&q=80&w=600',
    isPizza: false,
  },

  // --- DESSERTS ---
  {
    id: 'dessert_lava',
    name: 'Oven Warm Molten Fudge Lava',
    description: 'Indulgent personal chocolate lava cake with a crispy outer coating, holding a warm, rich, liquid dark chocolate core that oozes on first spoonful.',
    category: 'desserts',
    price: 390,
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&q=80&w=600',
    isPizza: false,
    isPopular: true,
  },
  {
    id: 'dessert_cookie',
    name: 'Pizza Master Giant Cookie',
    description: 'A huge, thick, sharing cookie baked in a cast-iron style pizza pan loaded with chocolate chips, served warm with rich chocolate fudge sauce.',
    category: 'desserts',
    price: 540,
    image: 'https://images.unsplash.com/photo-1588195538326-c5b1e9f80a1b?auto=format&fit=crop&q=80&w=600',
    isPizza: false,
  },

  // --- BEVERAGES ---
  {
    id: 'bev_cola_can',
    name: 'Coca Cola Can (345ml)',
    description: 'Ice cold carbonated red can refreshment.',
    category: 'beverages',
    price: 150,
    image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&q=80&w=600',
    isPizza: false,
  },
  {
    id: 'bev_sprite_can',
    name: 'Sprite Can (345ml)',
    description: 'Zesty lemon-lime crisp refreshment.',
    category: 'beverages',
    price: 150,
    image: spriteCanImg,
    isPizza: false,
  },
  {
    id: 'bev_coke_1_5l',
    name: 'Coca Cola (1.5 Litre)',
    description: 'Perfect companion for sharing pizza deals with multiple friends.',
    category: 'beverages',
    price: 260,
    image: coke15Img,
    isPizza: false,
  },
  {
    id: 'bev_water',
    name: 'Mineral Water (500ml)',
    description: 'Cold natural mineral water to refresh.',
    category: 'beverages',
    price: 90,
    image: 'https://images.unsplash.com/photo-1616118132534-381148898bb4?auto=format&fit=crop&q=80&w=600',
    isPizza: false,
  },

  // --- DIPS ---
  {
    id: 'dip_garlic_ranch',
    name: 'Pizza Master Garlic Ranch Dip',
    description: 'Our iconic creamy buttermilk garlic herb sauce pocket.',
    category: 'dips',
    price: 65,
    image: garlicRanchImg,
    isPizza: false,
    isPopular: true,
  },
  {
    id: 'dip_habanero',
    name: 'Fiery Pizza Master Habanero Dip',
    description: 'Thick, hot, spicy habanero cream dip to elevate crust bites.',
    category: 'dips',
    price: 65,
    image: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?auto=format&fit=crop&q=80&w=600',
    isPizza: false,
  },
  {
    id: 'dip_honey_mustard',
    name: 'Creamy Sweet Honey Mustard',
    description: 'A rich blend of sweet wild honey and sharp mustard seed dust.',
    category: 'dips',
    price: 65,
    image: 'https://images.unsplash.com/photo-1612182062633-9ff3b3598e96?auto=format&fit=crop&q=80&w=600',
    isPizza: false,
  },
];

export const PAKISTAN_CITIES = ['Karachi', 'Lahore', 'Islamabad', 'Rawalpindi', 'Faisalabad', 'Multan'];

export const CITY_AREAS: Record<string, string[]> = {
  Karachi: [
    'DHA Phase 1-8',
    'Clifton',
    'Gulshan-e-Iqbal',
    'Johar Block 1-20',
    'PECHS',
    'North Nazimabad',
    'Bahria Town Karachi',
    'KDA Schema 1',
  ],
  Lahore: [
    'DHA Phase 1-9',
    'Gulberg III',
    'Model Town',
    'Johar Town',
    'Faisal Town',
    'Bahria Town Lahore',
    'Samanabad',
    'Wapda Town',
  ],
  Islamabad: [
    'F-6 & F-7',
    'F-10 & F-11',
    'G-11 & G-13',
    'E-11',
    'Bahria Town Phase 1-8',
    'DHA Phase 1-5',
    'I-8 Sector',
  ],
  Rawalpindi: [
    'Saddar',
    'Westridge',
    'Satellite Town',
    'Chaklala Scheme III',
    'Bahria Town Rawalpindi',
  ],
  Faisalabad: [
    'Civil Lines',
    'People\'s Colony',
    'Samanabad Faisalabad',
    'D-Ground',
  ],
  Multan: [
    'Boson Road',
    'Gulgasht Colony',
    'Cantt Multan',
    'Shalimar Colony',
  ],
};
